# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-25 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0012_auto_20160325_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='description',
            field=models.CharField(blank=True, max_length=250, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='authority',
            field=models.CharField(blank=True, max_length=100, verbose_name='authority'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='source',
            field=models.URLField(blank=True, max_length=150, verbose_name='source'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='species',
            field=models.CharField(blank=True, max_length=100, verbose_name='species'),
        ),
    ]
