# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-25 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0013_auto_20160325_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='caption',
            field=models.CharField(blank=True, max_length=250, verbose_name='caption'),
        ),
    ]
