# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-25 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0014_auto_20160325_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_validated',
            field=models.BooleanField(default=False, verbose_name='validated'),
        ),
    ]
