# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-01 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0015_photo_is_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='admin_orig_image_tag',
            field=models.SlugField(default='dummy'),
        ),
    ]
