# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-01 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0016_photo_admin_orig_image_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='admin_orig_image_tag',
        ),
    ]
