# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-06 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0017_remove_photo_admin_orig_image_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='admin_thumbnail',
            field=models.SlugField(default='dummy'),
        ),
    ]
