# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-06 20:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0018_photo_admin_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='admin_thumbnail',
        ),
    ]
